insert into nuclide_element
values
(1,'H','Hydrogen','Wodór'),
(2,'He','Helium','Hel'),
(3,'Li','Lithium','Lit'),
(4,'Be','Beryllium','Beryl'),
(5,'B','Boron','Bor'),
(6,'C','Carbon','Węgiel'),
(7,'N','Nitrogen','Azot'),
(8,'O','Oxygen','Tlen'),
(9,'F','Fluorine','Fluor'),
(10,'Ne','Neon','Neon'),
(11,'Na','Sodium','Sód'),
(12,'Mg','Magnesium','Magnez'),
(13,'Al','Aluminum','Aluminium'),
(14,'Si','Silicon','Krzem'),
(15,'P','Phosphorus','Fosfor'),
(16,'S','Sulfur','Siarka'),			
(17,'Cl','Chlorine','Chlor')		,
(18,'Ar','Argon','Argon')			,
(19,'K','Potassium','Potas')		,
(20,'Ca','Calcium','Wapń')			,
(21,'Sc','Scandium','Skand')		,
(22,'Ti','Titanium','Tytan')		,
(23,'V','Vanadium','Wanad')			,
(24,'Cr','Chromium','Chrom')		,
(25,'Mn','Manganese','Mangan')		,
(26,'Fe','Iron','Żelazo')			,
(27,'Co','Cobalt','Kobalt')			,
(28,'Ni','Nickel','Nikiel')			,
(29,'Cu','Copper','Miedź')			,
(30,'Zn','Zinc','Cynk')				,
(31,'Ga','Gallium','Gal')			,
(32,'Ge','Germanium','German')		,
(33,'As','Arsenic','Arsen')			,
(34,'Se','Selenium','Selen')		,
(35,'Br','Bromine','Brom')			,
(36,'Kr','Krypton','Krypton')		,
(37,'Rb','Rubidium','Rubid')		,
(38,'Sr','Strontium','Stront')		,
(39,'Y','Yttrium','Itr')			,
(40,'Zr','Zirconium','Cyrkon')		,
(41,'Nb','Niobium','Niob')			,
(42,'Mo','Molybdenum','Molibden')	,
(43,'Tc','Technetium','Technet')	,
(44,'Ru','Ruthenium','Ruten')		,
(45,'Rh','Rhodium','Rod')			,
(46,'Pd','Palladium','Pallad')		,
(47,'Ag','Silver','Srebro')			,
(48,'Cd','Cadmium','Kadm')			,
(49,'In','Indium','Ind')			,
(50,'Sn','Tin','Cyna')				,
(51,'Sb','Antimony','Antymon')		,
(52,'Te','Tellurium','Tellur')		,
(53,'I','Iodine','Jod')				,
(54,'Xe','Xenon','Ksenon')			,
(55,'Cs','Cesium','Cez')			,
(56,'Ba','Barium','Bar')			,
(57,'La','Lanthanum','Lantan')		,
(58,'Ce','Cerium','Cer')			,
(59,'Pr','Praseodymium','Prazeodym'),
(60,'Nd','Neodymium','Neodym')		,
(61,'Pm','Promethium','Promethium')	,
(62,'Sm','Samarium','Samar')		,
(63,'Eu','Europium','Europium')		,
(64,'Gd','Gadolinium','Gadolin')	,
(65,'Tb','Terbium','Terb')			,
(66,'Dy','Dysprosium','Dysproz')	,
(67,'Ho','Holmium','Holm')			,
(68,'Er','Erbium','Erb')			,
(69,'Tm','Thulium','Tuł')			,
(70,'Yb','Ytterbium','Iterb')		,
(71,'Lu','Lutetium','Lutet')		,
(72,'Hf','Hafnium','Hafn')			,
(73,'Ta','Tantalum','Tantal')		,
(74,'W','Tungsten','Wolfram')		,
(75,'Re','Rhenium','Ren')			,
(76,'Os','Osmium','Osm')			,
(77,'Ir','Iridium','Iryd')			,
(78,'Pt','Platinum','Platyna')		,
(79,'Au','Gold','Złoto')			,
(80,'Hg','Mercury','Rtęć')			,
(81,'Tl','Thallium','Tal')			,
(82,'Pb','Lead','Ołów')				,
(83,'Bi','Bismuth','Bizmut')		,
(84,'Po','Polonium','Polon')		,
(85,'At','Astatine','Astat')		,
(86,'Rn','Radon','Radon')			,
(87,'Fr','Francium','Francium')		,
(88,'Ra','Radium','Rad')			,
(89,'Ac','Actinium','Aktyn')		,
(90,'Th','Thorium','Tor')			,
(91,'Pa','Protactinium','Protaktyn'),
(92,'U','Uranium','Uran')			,
(93,'Np','Neptunium','Neptunium')	,
(94,'Pu','Plutonium','Pluton')		,
(95,'Am','Americium','Ameryk')		,
(96,'Cm','Curium','Curium')			,
(97,'Bk','Berkelium','Berkelium')	,
(98,'Cf','Californium','Kalifornium')	,
(99,'Es','Einsteinium','Einsteinium')	,
(100,'Fm','Fermium','Fermium')			,
(101,'Md','Mendelevium','Mendelewium')	,
(102,'No','Nobelium','Nobelium')		,
(103,'Lr','Lawrencium','Lawrencium')	,
(104,'Rf','Rutherfordium','Rutherfordium')	,
(105,'Db','Dubnium','Dubnium')				,
(106,'Sg','Seaborgium','Seaborgium')		,
(107,'Bh','Bohrium','Bohrium')				,
(108,'Hs','Hassium','Hassium')				,
(109,'Mt','Meitnerium','Meitnerium')		,
(110,'Ds','Darmstadtium','Darmstadtium')	,
(111,'Rg','Roentgenium','Roentgenium')		,
(112,'Cn','Copernicium','Copernicium')		,
(113,'Nh','Nihonium','Nihonium')			,
(114,'Fl','Flerovium','Flerovium')			,
(115,'Mc','Moscovium','Moscovium')			,
(116,'Lv','Livermorium','Livermorium')		,
(117,'Ts','Tennessine','Tennessine')		,
(118,'Og','Oganesson','Oganesson')			
